const ADD_FAV = 'ADD_FAV';
const REMOVE_FAV = 'REMOVE_FAV';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';
const FILTRO = 'FILTR0';
const BY = 'BY';
const STATISTICS = 'STATISTICS';
const RESULT = 'RESULT';
const ADD_CHARACTER = 'ADD_CHARACTER';
const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
const ADD_STATISTICS = 'ADD_STATISTICS';

module.exports = {
  ADD_FAV,
  REMOVE_FAV,
  SHOW_LOADING,
  HIDE_LOADING,
  FILTRO,
  BY,
  STATISTICS,
  RESULT,
  ADD_CHARACTER,
  REMOVE_CHARACTER,
  ADD_STATISTICS,
};
